# Generated by Django 3.1.4 on 2020-12-01 19:54

import address.models
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('app', '0002_auto_20201130_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('formal_name', models.CharField(blank=True, max_length=100, verbose_name='Formal Name')),
                ('familiar_name', models.CharField(blank=True, max_length=100, verbose_name='Familiar Name')),
                ('greeting_name', models.CharField(blank=True, max_length=100, verbose_name='Greeting Name')),
                ('prefix', models.CharField(blank=True, max_length=100, verbose_name='Name Prefix')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('nick_name', models.CharField(blank=True, max_length=100, verbose_name='Nick Name')),
                ('suffix', models.CharField(blank=True, max_length=100, verbose_name='Name Suffix')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
