# Generated by Django 3.1.4 on 2020-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201203_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
